---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      shell: |
        sleep 200

    - name: "update apt packages"
      become: yes
      apt:
        update_cache: yes

    - name: "upgrade apt packages"
      become: yes
      apt:
        upgrade: yes

    - name: "install dependencies"
      apt:
        name: ["nodejs", "npm", "build-essential", "python3.8"]
        state: latest
        
    
    - name: "Install pm2"
      become: yes
      npm:
        name: pm2
        global: yes
        production: yes
        state: present

  roles:
    # Your code here