---
- name: Creates directory
  become: yes
  file:
    path: /var/web
    state: directory

- name: copy backend files
  become: yes
  copy:
    src: ../../../../../backend/dist
    dest: /var/web
    backup: yes